name: Continuous Integration
on: [push]
jobs:
  dockerlint:
    name: Dockerlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        uses: hadolint/hadolint-action@v1.5.0