name: Continuous Integration
on: [push, pull_request]
jobs:
  dockerlint:
    name: Dockerlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint
        uses: hadolint/hadolint-action@v1.5.0
  pylint:
    name: Pylint
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev
      - name: Pylint
        run: |
          pylint src